services:
  mariadb:
    container_name: tfm-mariadb
    image: mariadb:latest
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testeo
      - MYSQL_USER=testeo
      - MYSQL_PASSWORD=t3st30pwd$_
    volumes:
      - ./mariadb:/var/lib/mysql

  backend:
    container_name: tfm-backend
    build: ./backend
    ports:
      - "7000:7000"
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=testeo
      - MYSQL_USER=testeo
      - MYSQL_PASSWORD=t3st30pwd$_
      - HIBERNATE_DDL=update
    depends_on:
      - mariadb

  testeo:
    container_name: tfm-testeo
    build: ./testeo
    ports:
      - "7100:7100"
    depends_on:
      - backend
