spring:
  application:
    name: testeo
  jpa:
    hibernate.ddl-auto: ${HIBERNATE_DDL:validate}
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:testeo}
    username: ${MYSQL_USER:testeo}
    password: ${MYSQL_PASSWORD:testeopwd}

app:
  security:
    jwtCookieName: testeo
    jwtSecret: '======================TesTeo=Spring==========================='
    jwtExpirationMs: 86400000
server:
  port: 7000